name: Release Module

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release Realms & Reaches
        uses: rayners/foundry-module-actions@main
        with:
          node-version: '20'
          build-command: 'npm run build'
          working-directory: 'dist'
          module-files: 'module.js module.json styles/ templates/ languages/'