name: Test Module

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests for Node.js ${{ matrix.node-version }}
        uses: rayners/foundry-module-actions/test@v1
        with:
          node-version: ${{ matrix.node-version }}
          coverage: ${{ matrix.node-version == '18' }} # Only generate coverage for Node 18